### ISSUE TITLE
separate page for references to courses, quizzes and exercises

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#190]
- [x] remove references to courses, quizzes and exercises from each chapter
- [x] create a separate page for courses: "here is a list of courses that have used the version control book", then list a few details about the course (i.e., number of participants, target audience, when and where it took place, references to course slides, etc.)
- [ ] create a separate page for quizzes: list of all questions for each chapter
- [x] create a separate page for exercises

for the exercises, similar to the learning objectives, please use [quarto includes](https://quarto.org/docs/authoring/includes.html) so that we can flexibly place the exercises throughout the book, if needed.

could you maybe also draft "variants" of the exercises as we use them in the course? the idea would be to have a "catalogue" of exercises that one can draw from when conducting a course.

@konradpa, could you tackle this? thanks!

**Comment by lnnrtwttkhn** [comment]
oh, realized that we have a separate page for exercises already 😊

**Comment by lnnrtwttkhn** [comment]
Let's keep the quiz button for now, but maybe we move it to the end of the chapter?

**Comment by konradpa** [comment]
> * [ ]  create a separate page for quizzes: list of all questions for each chapter

For that could we just use #115 ? 
This adds a page with the embedded formR quizzes, which could make sense since we might continue to change some quiz questions.

**Comment by konradpa** [comment]
This is added by now
