### ISSUE TITLE
feature: generalize github chapters to "working with remote repositories"

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#191]
I think we should generalize the chapters on github to chapters about "remote repositories".

specifically, it would be nice to add instructions how to integrate with other repository hosting services, mainly [gitlab](https://about.gitlab.com/) which is used by many institutions, e.g., see [gitlab of university of hamburg](https://gitlab.rrz.uni-hamburg.de/users/sign_in).

the general idea would be to separate the github chapters into all the contents that are github-specific (e.g., how to create an account etc.) and those that apply to any remote repository (e.g,. push, pull, clone) etc.?

I am not sure yet, if it makes more sense to split this to separate "chapters" or "sections" or whether to use [tabsets](https://quarto.org/docs/interactive/layout.html#tabset-panel). I would probably play around and see what makes most sense.

this will likely be a medium to major overhaul of the github chapters, but worth it in the long run.

could you look into this @konradpa? thanks!

**Comment by konradpa** [comment]
This was added by #196
