### ISSUE TITLE
Add code snippets that create the result of an exercise and provide as download

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#224]
- [x] Create code snippets (Bash) that implement exercises
- [x] Execute code snippets and package resulting folder for download as `.zip` file (or some other format, TBD)
- [x] [Annotate](https://quarto.org/docs/authoring/code-annotation.html) code snippets to explain the solution

Thanks to @anamartinovici for the inspiration for this idea!

**Comment by lnnrtwttkhn** [comment]
@all-contributors please add @anamartinovici for ideas

**Comment by konradpa** [comment]
- [ ] Add intro and expaination text to exercise site
- [ ]  Save output of command line and add it below solutions
- [ ] rename the recipe repos specific to each exercise e.g. recipes_branches
