### ISSUE TITLE
Reorder chapter 4.1.1

### ISSUE THREAD

**Issue by justus-reihs** [lnnrtwttkhn/version-control-book#257]
In chapter 4.1.1 of the [version control book](https://lennartwittkuhn.com/version-control-book/chapters/setup.html#identifying-yourself) the content order is somewhat misleading. I suggest to first address the `FAQ for the username` and the `privacy preferences` and *after that* setting up `username` and `user email`.

**Comment by lnnrtwttkhn** [comment]
Thanks for the suggestion @justus-reihs, I agree that makes sense. Will be fixed by #265.

**Comment by lnnrtwttkhn** [comment]
https://github.com/all-contributors please add @justus-reihs for bug, ideas

**Comment by lnnrtwttkhn** [comment]
@all-contributors please add @justus-reihs for bug, ideas
