### ISSUE TITLE
Found typos

### ISSUE THREAD

**Issue by rezahakimazar** [lnnrtwttkhn/version-control-book#284]
1. In section 1.3.1, in the sentence "One you realize that this is becoming complicated, you create a meta document that you want to use to keep track of the project progress. ", "One" should be replaced with "Once".
2. In the same paragraph, "Then you realize that you software has bugs ...", "you software" should be replaced with "your software".

**Comment by lnnrtwttkhn** [comment]
Thank you @rezahakimazar for catching these typos. Would you be up to fix them in a PR? Happy to help with the workflow (I think this is the first time you are editing the book, right?). Thanks!

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
I can fix that @lnnrtwttkhn @rezahakimazar

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
pull request opened
