### ISSUE TITLE
Correct typos

### ISSUE THREAD

**Issue by lieku** [lnnrtwttkhn/version-control-book#295]
- [ ] 6.7.1 [...] you can also create "a" global .gitignore
- [ ] 8.4.0.2 add changes "to" your repository
- [ ] 10.1.1 Once created, a tag is generally immutable"."
- [ ] 11.5.8 [...] general inquiries "." Each
- [ ] 11.5.2.5 you "can" check out
- [ ] Figure 12.5: correct from R Studio to GitKraken
- [ ] cheatsheet under branches: git stash: "Stashes" changes for later use

**Comment by lnnrtwttkhn** [comment]
Fixed in #307
