### ISSUE TITLE
dumping ideas

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#49]
sorry, this is not very elegant but I'm quickly dumping a few notes heres:

- [x] "recipes task": (1) add your favorite recipes, (2) add a recipe that you *don't* like /this will be removed later)
- [x] `.gitignore`: explain the difference between global and project-specific `.gitignore`
- [x] `.gitignore`: explain what `.DS_Store` is (for mac users only)
- [x] add more categories to the chapters so they show up in the `contents` page
- [x] labels for difficulty / experience level: `beginner`, `intermediate`, `advanced`
- [x] create one page with all the cheatsheets

@konradpa, could you please review these points and let me know what is already included in the book and what we still could add? let me know if anything is unclear! thanks!

**Comment by konradpa** [comment]
This is all fixed by now
