### ISSUE TITLE
prepare for session 3: git basics

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#55]
- [x] focus on vim (which is the default editor)
- [x] explain relationship between git, vim and other GUI text editors on the computer
- [x] explain the difference between plain text and Word
- [x] basics on how to use vim
- [x] discuss differences between local and global git config
- [x] explain to use same email for git and github
- [x] maybe skip account creation on github
- [ ] clarify exercises for creating a recipe
- [ ] `.gitignore` optional?
- [ ] `.gitignore` discussion / ideas
  - keep repositories small / only commit files that are really needed
  - reproducibility: don't add files that can be easily regenerated from the committed code
  - don't add files that are not relevant to other users, e.g., editor configuration files etc.
- [x] differences between local and global `.gitignore`
- [ ] add warning: don't create a new repo e.g., in your user directory
- [x] use `ls -a` command to show the hidden `.git` folder (add link to command line chapter)
- [x] add warning: don't mess with the `.git` folder
- [ ] add `git init my-project`
- [ ] add mini-quiz: how to create a project folder, either (1) `mkdir my-project && cd my-project & git init` or `git init my-project`
- [ ] setup session as live coding session
- [x] separate installation and setup chapter
- [x] move creation of github account to github chapter
- [x] edit installation and setup survey
- [ ] send email to ask to verify installation and complete installation survey
- [ ] `git` commands always refer to the "closest" `.git` file. clarify that.
- [ ] beware of nested `.git` repositories. explain if it's possible to have nested git repositories
- [ ] decide for default text editors on Windows (Notepad) and macOS (TextEdit)
- [ ] demonstrate interaction between editing text files in vim and through the GUI texteditor
- [ ] explain what the staging area is, see e.g., https://youtu.be/HMqUFlu0gFc?t=228
- [ ] think about whether to add STOP signs to the chapter for course participants!

**Comment by lnnrtwttkhn** [comment]
largely addressed in #57. keeping this open still as not all open points are addressed yet.

**Comment by konradpa** [comment]
This is all irrelevant/added by now
