### ISSUE TITLE
preparation for session 4

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#58]
- [ ] play around with basic git commands, vim etc.
- [ ] make multiple commits in one repository
- [x] compare commits across history
- [x] `.gitignore`
- [x] example use-case: tracking word documents in git
- [x] discussion: advantages / disadvantages of git in combination with binary files like word
- [x] relation to `.gitignore`: word create a temporary file, something like "~$mypaper.docx"
- [x] gateway to markdown session (session 5): why it's not great to track binary files in git and what are the alternatives to word
- [x] `git commit` : explain that one can also add a more detailed description, e.g., `git commit -m "commit message" -m "longer description"`
- [x] idea that one can use the description of the commit message to document changes in binary files in a bit more detail
- [ ] discuss different workflows of using `git add`, `git commit` etc.
- [x] make minimal changes
- [x] encapsulate only neccessary changes in commit
- [x] reproducibility: recreate temporary files from changes in code
- [x] explain repeated `--amend`
- [ ] add graphics that explain staging environment vs. commit

**Comment by konradpa** [comment]
All irrelevant/added by now
