### ISSUE TITLE
Ideas for Session 9 (GitHub)

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-book#70]
- [x] Layout
- [x] Decide on PAT or SSH for verification
- [x] @lnnrtwttkhn add SSH key section
- [x] 1. Pushing recipe repo to GitHub, 2. Creating repo on Github and clone it
- [x] Switching forking and cloning in book
- [x] Demoing cloning
- [x] Repository setting - add section in book (private/public, README)
- [x] Creating EMPTY repository to be able to push existing repo
- [x] Creating github organization?
- [x] Exercise: pushing existing repo to GitHub, clone it to different location on PC, make changes in clone, push changes, pull from original location
- [x] Extra Exercise: Create branch and push branch
- [x] Demo/Explain differences between git fetch and git pull
- [x] Put forking in end of book
- [x] Forking/Templaterepos/GitHub alternatives/Branch protection/git blame as extra content
- [x] Send email: Creating GitHub account
- [x] Session 10: Pull requests, collab, Github flow?
- [x] Figure out how to collaborate easily among course members - organization?
- [x] Section about GitHub flow?
- [x] Create slides

**Comment by lnnrtwttkhn** [comment]
all done. closing.
