### ISSUE TITLE
Notes for session 10

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-book#79]
- Terminal Farbkodierung Bedeutung?

- Absoluter Pfad muss. in ``Anführungszeichen nicht "" - auf GitBash

- idee: Wie "git init" rückgängig machen? == "rm -rf .git"

- Use "echo" to write in file

- Dateinamen: Keine Leerzeichen

- Von CLI Datei öffnen

- Cat command

- Meldung: LD will be replaced by CRLF

- git commit filename -> skips git add (staging area)

- using git checkout to delete unstaged changes

**Comment by lnnrtwttkhn** [comment]
Re the warning message: https://stackoverflow.com/questions/17628305/windows-git-warning-lf-will-be-replaced-by-crlf-is-that-warning-tail-backwar

**Comment by konradpa** [comment]
This all added/irrelevant or summarized in #80 by now

**Comment by lnnrtwttkhn** [comment]
Are you sure all of this is included? I bet you have a better overview than me, but for example I can't remember that we've added a note about the warning.

**Comment by konradpa** [comment]
> Are you sure all of this is included? I bet you have a better overview than me, but for example I can't remember that we've added a note about the warning.

Thats true, these issues were not included in #80 for some reason.  Now they are
