### ISSUE TITLE
add section on README

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#83]
@konradpa, we should a section (maybe in the GitHub chapter) on the README file, what it is, how to create it, best practices etc.

if you have the time, could you make a draft? thanks!

**Comment by konradpa** [comment]
> @konradpa, we should a section (maybe in the GitHub chapter) on the README file, what it is, how to create it, best practices etc.
> 
> if you have the time, could you make a draft? thanks!

Sure, there is already a callout box in the GitHub chapter about the README, I can expand on this.

**Comment by lnnrtwttkhn** [comment]
Fixed by #87. Closing.
